backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
media_folder: "public/images/uploads"
public_folder: "/images/uploads"


collections:
  - name: "products"
    label: "Products"
    folder: "_products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Brand", name: "brand", widget: "string"}
      - {label: "Product Name", name: "name", widget: "string"}
      - {label: "Price (GHS)", name: "price", widget: "number"}
      - {label: "Category", name: "category", widget: "select", options: ["sneakers", "tops", "jeans", "accessories"]}
      - {label: "Photo", name: "image", widget: "image"}
      - {label: "Badge", name: "badge", widget: "select", options: ["", "new", "hot"], default: ""}
      - {label: "On Sale?", name: "sale", widget: "boolean", default: false}
